.\" Manpage for dhcpcanon.
.\" Contact ju@riseup.net to correct errors or typos.
.TH man 8 "25 Nov 2016" "1.0" "dhcpcanon man page"
.SH NAME
dhcpcanon \- DHCP Client Anonymity profile
.SH SYNOPSIS
dhcpcanon [-h] [-d] [-l LEASE] [-v] [interface]
.SH DESCRIPTION
dhcpcanon is a DCHP client implementation of the DHCP Anonymity Profile (RFC7844).
using Scapy Automaton.
.SH OPTIONS
The options which apply to the dhcpcanon command are:

-h, --help
    Show help message and exit.

-d, --debug
    Show debug messages.

-l, --lease LEASE
    Custom lease time.

-v, --version
    Show version.
.SH AUTHOR
ju xor (ju@riseup.net)
